version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: planificador_db
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:80  
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: planificador_db
      MYSQL_ROOT_PASSWORD: root
    ports:  
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
