export const titlesByRoute = {
  "/app/home": "Home",
  "/app/users": "Usuarios",
  "/app/products": "Productos",
  "/app/services": "Servicios",
  "/app/customers": "Clientes",
  "/app/rates": "Tarifas",
  "/app/orders": "Orden de Servicio (OS)",
  "/app/orders-input": "Ingreso",
  "/app/orders-output": "Salida",
  "/app/orders-truck": "Ingresar Patente",
  "/app/orders-weight-input": "Pesaje de Entrada",
  "/app/orders-weight-output": "Pesaje de Salida",
  "/app/orders-confirm": "Confirmar Orden de Servicio (OS)",
};
