export const titlesByRoute = {
  "/dashboard": "Dashboard",
  "/users": "Usuarios",
  "/products": "Productos",
  "/services": "Servicios",
  "/customers": "Clientes",
  "/rates": "Tarifas",
  "/orders": "Orden de Servicio (OS)",
  "/orders-input": "Ingreso",
  "/orders-output": "Salida",
  "/orders-truck": "Registrar Patente",
  "/orders-weight-input": "Pesaje de Entrada",
  "/orders-weight-output": "Pesaje de Salida",
  "/orders-confirm": "Confirmar Orden de Servicio (OS)",
};
