export { default as CustomerPage } from "./CustomerPage/CustomerPage.jsx";
export { default as DashboardPage } from "./DashboardPage/DashboardPage.jsx";
export { default as ErrorPage } from "./ErrorPage/ErrorPage.jsx";
export { default as LoginPage } from "./LoginPage/LoginPage.jsx";
export { default as ProductPage } from "./ProductPage/ProductPage.jsx";
// export { default as RegisterClientPage } from "./RegisterClientPage/RegisterClientPage.jsx";
export { default as OrderConfirmPage } from "./OrderPage/OrderConfirmPage.jsx";
export { default as OrderInputPage } from "./OrderPage/OrderInputPage.jsx";
export { default as OrderOutputPage } from "./OrderPage/OrderOutputPage.jsx";
export { default as OrderWeightInputPage } from "./OrderPage/OrderWeightInputPage.jsx";
export { default as OrderWeightOutputPage } from "./OrderPage/OrderWeightOutputPage.jsx";
export { default as OrderPage } from "./OrderPage/OrderPage.jsx";
export { default as OrderTruckPage } from "./OrderPage/OrderTruckPage.jsx";
export { default as RatePage } from "./RatePage/RatePage.jsx";
export { default as ServicePage } from "./ServicePage/ServicePage.jsx";
export { default as UserPage } from "./UserPage/UserPage.jsx";
export { default as UserProfile } from "./UserPage/UserProfile.jsx";
